# Day 26 - NumPy and Vectorized Computing

This notebook covers:
- Why NumPy is useful for data engineering
- Python lists vs NumPy arrays
- Memory layout and memory efficiency
- Array basics: shape, size, dtype, ndim
- Multi-dimensional arrays
- Vectorization
- Broadcasting
- Universal functions
- Aggregations
- Data engineering examples
- Interview questions


## 1. Import NumPy


In [ ]:
import numpy as np

print(np.__version__)


2.0.2


## 2. Python List vs NumPy Array

Python lists are flexible general-purpose containers.

NumPy arrays are optimized for numerical computing.


In [ ]:
python_list = [10, 20, 30, 40, 50]
numpy_array = np.array([10, 20, 30, 40, 50])

print(python_list)
print(numpy_array)

print(type(python_list))
print(type(numpy_array))


[10, 20, 30, 40, 50]
[10 20 30 40 50]
<class 'list'>
<class 'numpy.ndarray'>


## 3. Python Lists Can Store Mixed Types

A Python list can store multiple data types in the same collection.


In [ ]:
mixed_list = [101, "Riya", 250.75, True]

print(mixed_list)

for value in mixed_list:
    print(value, type(value))


[101, 'Riya', 250.75, True]
101 <class 'int'>
Riya <class 'str'>
250.75 <class 'float'>
True <class 'bool'>


## 4. NumPy Arrays Usually Store One Data Type

NumPy arrays are most efficient when all elements share the same data type.


In [ ]:
numeric_array = np.array([101, 250, 300])
print(numeric_array)
print(numeric_array.dtype)

mixed_array = np.array([101, 250.75, True])
print(mixed_array)
print(mixed_array.dtype)


[101 250 300]
int64
[101.   250.75   1.  ]
float64


## 5. Memory Efficiency

A NumPy array stores numeric values compactly.

A Python list stores references to Python objects.


In [ ]:
import sys

numbers_list = list(range(1000000))
numbers_array = np.array(numbers_list)

print("Python list container size:", sys.getsizeof(numbers_list))
print("NumPy array data size:", numbers_array.nbytes)
print("NumPy dtype:", numbers_array.dtype)


Python list container size: 8000056
NumPy array data size: 8000000
NumPy dtype: int64


## 6. Python List Stores Object References

The list itself stores references.

Each Python integer is a separate object.


In [ ]:
sample_list = [10, 20, 30]

print("List object size:", sys.getsizeof(sample_list))

for value in sample_list:
    print("value:", value, "object size:", sys.getsizeof(value), "id:", id(value))


List object size: 88
value: 10 object size: 28 id: 11645640
value: 20 object size: 28 id: 11645960
value: 30 object size: 28 id: 11646280


## 7. NumPy Array Memory Details

NumPy arrays expose memory-related attributes.


In [ ]:
arr = np.array([10, 20, 30], dtype=np.int64)

print(arr)
print("dtype:", arr.dtype)
print("itemsize:", arr.itemsize)
print("size:", arr.size)
print("nbytes:", arr.nbytes)


[10 20 30]
dtype: int64
itemsize: 8
size: 3
nbytes: 24


## 8. Why NumPy Is Faster for Math

NumPy operations are implemented in optimized low-level code.

This reduces Python loop overhead.


In [ ]:
import time

n = 1_000_000

list_a = list(range(n))
list_b = list(range(n))

array_a = np.array(list_a)
array_b = np.array(list_b)

start = time.time()
list_result = [list_a[i] + list_b[i] for i in range(n)]
end = time.time()
print("Python list addition time:", end - start)

start = time.time()
array_result = array_a + array_b
end = time.time()
print("NumPy array addition time:", end - start)


Python list addition time: 0.18518853187561035
NumPy array addition time: 0.005753278732299805


## 9. Data Engineering Example: Transaction Amount Processing

Vectorized operations can process entire batches of numeric values.


In [ ]:
transaction_amounts = np.array([100.50, 250.75, 900.00, 1200.25, 50.00])

tax_rate = 0.18

tax_amounts = transaction_amounts * tax_rate
final_amounts = transaction_amounts + tax_amounts

print("transactions:", transaction_amounts)
print("tax:", tax_amounts)
print("final amounts:", final_amounts)


transactions: [ 100.5   250.75  900.   1200.25   50.  ]
tax: [ 18.09   45.135 162.    216.045   9.   ]
final amounts: [ 118.59   295.885 1062.    1416.295   59.   ]


## 10. Creating Arrays


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros(5)
arr3 = np.ones(5)
arr4 = np.arange(1, 10)
arr5 = np.linspace(0, 1, 5)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)


[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


# 11. Array Attributes

Important attributes:
- shape
- size
- dtype
- ndim


In [ ]:
sales = np.array([100, 200, 300, 400, 500])

print("array:", sales)
print("shape:", sales.shape)
print("size:", sales.size)
print("dtype:", sales.dtype)
print("ndim:", sales.ndim)


array: [100 200 300 400 500]
shape: (5,)
size: 5
dtype: int64
ndim: 1


# 12. Two-Dimensional Arrays

2D arrays can represent matrix-like data.

Example:
Rows = stores
Columns = days


In [ ]:
store_sales = np.array([
    [1000, 1200, 1300],
    [900, 1100, 1050],
    [1500, 1600, 1700]
])

print(store_sales)
print("shape:", store_sales.shape)
print("rows:", store_sales.shape[0])
print("columns:", store_sales.shape[1])
print("ndim:", store_sales.ndim)


[[1000 1200 1300]
 [ 900 1100 1050]
 [1500 1600 1700]]
shape: (3, 3)
rows: 3
columns: 3
ndim: 2


## 13. Indexing 2D Arrays


In [ ]:
print("Store 1 all days:", store_sales[0])
print("Day 2 across stores:", store_sales[:, 1])
print("Store 2 Day 3:", store_sales[1, 2])


Store 1 all days: [1000 1200 1300]
Day 2 across stores: [1200 1100 1600]
Store 2 Day 3: 1050


## 14. Reshaping Arrays


In [ ]:
values = np.arange(1, 13)

matrix = values.reshape(3, 4)

print(values)
print(matrix)
print(matrix.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


## 15. Vectorization

Vectorization means applying an operation to an entire array at once instead of writing explicit Python loops.


In [ ]:
amounts = np.array([100, 200, 300, 400])

discounted_amounts = amounts * 0.90

print(discounted_amounts)


[ 90. 180. 270. 360.]


## 16. Loop vs Vectorized Operation


In [ ]:
amounts_list = [100, 200, 300, 400]

discounted_loop = []

for amount in amounts_list:
    discounted_loop.append(amount * 0.90)

print(discounted_loop)

amounts_array = np.array([100, 200, 300, 400])
discounted_vectorized = amounts_array * 0.90

print(discounted_vectorized)


[90.0, 180.0, 270.0, 360.0]
[ 90. 180. 270. 360.]


## 17. Data Engineering Example: Currency Conversion


In [ ]:
prices_usd = np.array([10.5, 25.0, 100.75, 250.0])
usd_to_inr_rate = 83.2

prices_inr = prices_usd * usd_to_inr_rate

print(prices_inr)


[  873.6  2080.   8382.4 20800. ]


## 18. Boolean Filtering

NumPy can apply conditions to entire arrays.


In [ ]:
order_amounts = np.array([100, -50, 250, 0, 500, 750])

valid_mask = order_amounts > 0

print(valid_mask)
print(order_amounts[valid_mask])


[ True False  True False  True  True]
[100 250 500 750]


## 19. Data Engineering Example: Filter Valid Transactions


In [ ]:
transaction_amounts = np.array([100.5, -20.0, 450.0, 0.0, 999.99, -10.0])

valid_transactions = transaction_amounts[transaction_amounts > 0]

print(valid_transactions)
print("valid count:", valid_transactions.size)
print("valid total:", np.sum(valid_transactions))


[100.5  450.   999.99]
valid count: 3
valid total: 1550.49


## 20. Broadcasting

Broadcasting allows NumPy to apply operations between arrays of compatible but different shapes.


In [ ]:
amounts = np.array([100, 200, 300])

service_fee = 10

final_amounts = amounts + service_fee

print(final_amounts)


[110 210 310]


## 21. Broadcasting Across Rows


In [ ]:
sales_matrix = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900]
])

daily_bonus = np.array([10, 20, 30])

adjusted_sales = sales_matrix + daily_bonus

print(adjusted_sales)


[[110 220 330]
 [410 520 630]
 [710 820 930]]


## 22. Broadcasting Across Columns


In [ ]:
sales_matrix = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900]
])

store_adjustment = np.array([[1.10], [0.95], [1.05]])

adjusted_by_store = sales_matrix * store_adjustment

print(adjusted_by_store)


[[110. 220. 330.]
 [380. 475. 570.]
 [735. 840. 945.]]


## 23. Data Engineering Example: Store-Level Tax Rates

Rows represent stores.

Columns represent product sales.

Each store has a different tax rate.


In [ ]:
store_product_sales = np.array([
    [1000, 2000, 1500],
    [1200, 1800, 1600],
    [900, 1400, 1300]
])

store_tax_rates = np.array([[0.18], [0.12], [0.05]])

tax_values = store_product_sales * store_tax_rates
final_values = store_product_sales + tax_values

print("tax values:")
print(tax_values)

print("final values:")
print(final_values)


tax values:
[[180. 360. 270.]
 [144. 216. 192.]
 [ 45.  70.  65.]]
final values:
[[1180. 2360. 1770.]
 [1344. 2016. 1792.]
 [ 945. 1470. 1365.]]


## 24. Universal Functions

Universal functions, or ufuncs, are fast element-wise NumPy functions.

Examples:
- np.add
- np.sqrt
- np.multiply
- np.abs
- np.power


In [ ]:
values = np.array([1, 4, 9, 16, 25])

print(np.sqrt(values))
print(np.add(values, 10))
print(np.multiply(values, 2))
print(np.power(values, 2))


[1. 2. 3. 4. 5.]
[11 14 19 26 35]
[ 2  8 18 32 50]
[  1  16  81 256 625]


## 25. More ufunc Examples


In [ ]:
errors = np.array([-5, -2, 0, 3, 8])

print("absolute:", np.abs(errors))
print("squared:", np.power(errors, 2))
print("clipped:", np.clip(errors, 0, 5))


absolute: [5 2 0 3 8]
squared: [25  4  0  9 64]
clipped: [0 0 0 3 5]


## 26. Aggregations

Aggregations summarize data.


In [ ]:
daily_revenue = np.array([1000, 1500, 1200, 1800, 2000])

print("sum:", np.sum(daily_revenue))
print("mean:", np.mean(daily_revenue))
print("min:", np.min(daily_revenue))
print("max:", np.max(daily_revenue))
print("std:", np.std(daily_revenue))


sum: 7500
mean: 1500.0
min: 1000
max: 2000
std: 368.7817782917155


## 27. Aggregations on 2D Arrays

For a 2D array:
- axis=0 aggregates down columns
- axis=1 aggregates across rows


In [ ]:
store_sales = np.array([
    [1000, 1200, 1300],
    [900, 1100, 1050],
    [1500, 1600, 1700]
])

print("total per day:", np.sum(store_sales, axis=0))
print("total per store:", np.sum(store_sales, axis=1))
print("average per day:", np.mean(store_sales, axis=0))
print("average per store:", np.mean(store_sales, axis=1))


total per day: [3400 3900 4050]
total per store: [3500 3050 4800]
average per day: [1133.33333333 1300.         1350.        ]
average per store: [1166.66666667 1016.66666667 1600.        ]


## 28. Data Quality Checks with NumPy


In [ ]:
amounts = np.array([100, 250, -50, 0, 700, 900, -10])

invalid_mask = amounts <= 0
valid_mask = amounts > 0

print("invalid values:", amounts[invalid_mask])
print("valid values:", amounts[valid_mask])
print("invalid count:", np.sum(invalid_mask))
print("valid count:", np.sum(valid_mask))


invalid values: [-50   0 -10]
valid values: [100 250 700 900]
invalid count: 3
valid count: 4


## 29. Outlier Detection

A simple outlier rule can use mean and standard deviation.


In [ ]:
latency_ms = np.array([120, 130, 125, 140, 135, 500, 128, 132])

mean_latency = np.mean(latency_ms)
std_latency = np.std(latency_ms)

threshold = mean_latency + 2 * std_latency

outliers = latency_ms[latency_ms > threshold]

print("mean:", mean_latency)
print("std:", std_latency)
print("threshold:", threshold)
print("outliers:", outliers)


mean: 176.25
std: 122.49770406011697
threshold: 421.24540812023395
outliers: [500]


## 30. Normalize Numeric Feature

Normalization is common before analytics and machine learning.


In [ ]:
amounts = np.array([100, 200, 300, 400, 500])

min_value = np.min(amounts)
max_value = np.max(amounts)

normalized = (amounts - min_value) / (max_value - min_value)

print(normalized)


[0.   0.25 0.5  0.75 1.  ]


## 31. Missing Values with NumPy

NumPy uses np.nan for missing numeric values.


In [ ]:
values = np.array([100.0, 200.0, np.nan, 400.0])

print(values)
print(np.isnan(values))
print(np.nanmean(values))
print(np.nansum(values))


[100. 200.  nan 400.]
[False False  True False]
233.33333333333334
700.0


## 32. Replacing Missing Values


In [ ]:
values = np.array([100.0, 200.0, np.nan, 400.0])

mean_value = np.nanmean(values)

clean_values = np.where(np.isnan(values), mean_value, values)

print(clean_values)


[100.         200.         233.33333333 400.        ]


# Practice Problems


## 33. Practice Problem 1: Create an Array

Create a NumPy array from a list of order amounts.

Print:
- array
- shape
- size
- dtype


In [ ]:
order_amounts = [100, 250, 300, 450, 500]

# Write solution here


## 34. Practice Problem 2: Vectorized Tax Calculation

Given an array of product prices, calculate 18 percent GST and final price.


In [ ]:
prices = np.array([1000, 2500, 5000, 7500])

# Write solution here


## 35. Practice Problem 3: Filter Invalid Transactions

Given transaction amounts, keep only values greater than 0.


In [ ]:
transactions = np.array([500, -100, 250, 0, 900, -20])

# Write solution here


## 36. Practice Problem 4: Store-Level Revenue

Rows represent stores, columns represent days.

Calculate:
- total revenue per store
- total revenue per day


In [ ]:
sales = np.array([
    [1000, 1200, 1100],
    [900, 950, 1000],
    [1500, 1600, 1700]
])

# Write solution here


## 37. Practice Problem 5: Broadcasting Discount

Apply a different discount rate to each product column.


In [ ]:
product_prices = np.array([
    [1000, 2000, 3000],
    [1500, 2500, 3500]
])

discount_rates = np.array([0.10, 0.20, 0.05])

# Write solution here


## 38. Practice Problem 6: Replace Missing Values

Replace missing values with the mean of available values.


In [ ]:
values = np.array([10.0, 20.0, np.nan, 40.0, np.nan, 60.0])

# Write solution here


# Interview Questions


## 39. Why is a NumPy array more memory-efficient than a Python list?

A Python list stores references to Python objects.

Each object has extra overhead.

A NumPy array stores values of the same type in a compact contiguous memory block.

This makes NumPy arrays more memory-efficient for numerical data.


## 40. Explain Broadcasting with an Example

Broadcasting allows NumPy to perform operations on arrays with different shapes when they are compatible.

Example:

```python
arr = np.array([100, 200, 300])
arr + 10
```

The scalar value 10 is applied to every element.

Result:

```python
[110, 210, 310]
```


## 41. What Does Vectorization Mean in Data Processing?

Vectorization means applying operations to an entire array at once instead of using explicit Python loops.

Example:

```python
amounts * 1.18
```

This applies the operation to all elements.

Benefits:
- faster computation
- cleaner code
- less Python loop overhead
- optimized low-level execution


## 42. Why Are Python Lists Slower for Math?

Python lists are general-purpose containers.

They store references to objects and support mixed data types.

Mathematical operations require Python to process each element individually.

NumPy arrays use fixed-type contiguous memory and optimized compiled operations.


## 43. What Is a ufunc?

A ufunc, or universal function, is a fast NumPy function that operates element-wise on arrays.

Examples:
- np.add
- np.sqrt
- np.multiply
- np.abs
- np.log

ufuncs are implemented efficiently and support broadcasting.


## 44. Summary

Key takeaways:
- NumPy arrays are efficient for numerical data.
- NumPy arrays store same-type values compactly.
- Vectorization avoids explicit Python loops.
- Broadcasting applies operations across compatible shapes.
- ufuncs provide fast element-wise operations.
- Aggregations summarize arrays efficiently.
- NumPy is a foundation for Pandas, machine learning, and data processing libraries.
